"""JFG PDF Generator v1

Generates simple, professional PDFs for the JFG Project.

Usage:

    pip install reportlab
    python scripts/jfg_pdf_generator.py \
        --input docs/templates/JFG_Sample_Report.json \
        --output exports/JFG_Sample_Report.pdf
"""

import json
import argparse
from pathlib import Path

from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch


def draw_wrapped_text(c, text, x, y, max_width, leading=14, font_name="Helvetica", font_size=11):
    c.setFont(font_name, font_size)
    words = text.split()
    line = []
    for word in words:
        test_line = " ". ".join(line + [word])
        if c.stringWidth(test_line, font_name, font_size) <= max_width:
            line.append(word)
        else:
            c.drawString(x, y, " ".join(line))
            y -= leading
            line = [word]
    if line:
        c.drawString(x, y, " ".join(line))
        y -= leading
    return y


def generate_pdf(config, output_path):
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    c = canvas.Canvas(str(output_path), pagesize=letter)
    width, height = letter

    margin_left = 1 * inch
    margin_right = 1 * inch
    margin_top = 1 * inch
    margin_bottom = 1 * inch

    x = margin_left
    max_width = width - margin_left - margin_right
    y = height - margin_top

    title = config.get("title", "JFG Project Report")
    subtitle = config.get("subtitle", "")
    sections = config.get("sections", [])
    footer = config.get("footer", "Generated by JFG PDF Generator v1")

    c.setFont("Helvetica-Bold", 18)
    c.drawString(x, y, title)
    y -= 24

    if subtitle:
        c.setFont("Helvetica-Oblique", 12)
        c.drawString(x, y, subtitle)
        y -= 20

    y -= 10

    for section in sections:
        heading = section.get("heading", "")
        paragraphs = section.get("paragraphs", [])

        if heading:
            c.setFont("Helvetica-Bold", 13)
            c.drawString(x, y, heading)
            y -= 18

        for paragraph in paragraphs:
            if y < margin_bottom + 60:
                c.showPage()
                y = height - margin_top
            y = draw_wrapped_text(
                c,
                paragraph,
                x,
                y,
                max_width,
                leading=14,
                font_name="Helvetica",
                font_size=11,
            )
            y -= 6

        y -= 10

        if y < margin_bottom + 60:
            c.showPage()
            y = height - margin_top

    c.setFont("Helvetica-Oblique", 9)
    c.drawString(margin_left, margin_bottom - 0.3 * inch, footer)

    c.showPage()
    c.save()


def main():
    parser = argparse.ArgumentParser(description="Generate a PDF report for the JFG Project.")
    parser.add_argument("--input", "-i", required=True, help="Path to JSON config")
    parser.add_argument("--output", "-o", required=True, help="Output PDF path")
    args = parser.parse_args()

    config_path = Path(args.input)
    if not config_path.is_file():
        raise SystemExit(f"Input config not found: {config_path}")

    with config_path.open() as f:
        config = json.load(f)

    generate_pdf(config, args.output)
    print(f"PDF generated at: {args.output}")


if __name__ == "__main__":
    main()
